FROM node:7.3.0

RUN apt-get install bash

RUN mkdir -p /usr/src/app
RUN mkdir -p /os/bin
WORKDIR /usr/src/app

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

COPY /server/package.json /usr/src/app

RUN npm install

CMD npm start