version: '2'
services:
  dev:
    hostname: wf_api
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile.build
    ports:
        - "8090:8090"
    volumes:
        - ../../src:/usr/src/app/src
        - ../../static/:/usr/src/app/static
        - ../../test/:/usr/src/app/test
        - ../../config/:/usr/src/app/config
        - ../../dist/:/usr/src/app/dist
    command: "/os/bin/watch.sh"
    links:
      - dev-server:my_wf_api
  dev-server:
    hostname: wf_api_server
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile.server
    ports:
        - "6819:9912"
    volumes:
        - ../../server/src:/usr/src/app/src

  tester:
    hostname: wf_api
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile.build
    volumes:
        - ../../src:/usr/src/app/src
        - ../../static/:/usr/src/app/static
        - ../../test/:/usr/src/app/test
        - ../../config/:/usr/src/app/config
        - ../../dist/:/usr/src/app/dist
    command: "/os/bin/test.sh"